=head1 NAME

Task::BeLike::Plicease - Modules Plicease Uses.

=head1 VERSION

version 0.34

=head1 SYNOPSIS

 cpanm Task::BeLike::Plicease

=head1 DESCRIPTION

Modules that I like to have installed when I am doing my Perl thing.

Some modules are not installed on MSWin32 or cygwin if they are known
not to work on those platforms.  See the Makefile.PL or dist.ini that
comes with this distribution for details.

=over 4

=item *

AnyEvent

=item *

AnyEvent::Ident

=item *

AnyEvent::Open3::Simple

=item *

App::Ack

=item *

App::cpanminus

=item *

App::RegexFileUtils

=item *

Authen::Simple

=item *

autodie

=item *

Clustericious

=item *

Clustericious::Client

=item *

Clustericious::Config

=item *

Clustericious::Log

=item *

Crypt::PasswdMD5

=item *

Data::Downloader

=item *

DBD::mysqlPP

=item *

DBD::PgPP

=item *

DBD::SQLite

=item *

DBI

=item *

Devel::StackTrace

=item *

Digest::MD5

=item *

File::chdir

=item *

File::IgnoreReadonly

=item *

File::Touch

=item *

HTTP::Tiny

=item *

IPC::Run

=item *

JSON

=item *

JSON::XS

=item *

Lingua::Alphabet::Phonetic::LAPD

=item *

local::lib

=item *

Log::Log4perl

=item *

Module::CoreList

=item *

Module::Which

=item *

Mojo::JSON::Any

=item *

Mojolicious

=item *

Mojolicious::Plugin::Ident

=item *

Mojolicious::Plugin::RenderFile

=item *

Mojolicious::Plugin::SslAuth

=item *

Mojolicious::Plugin::TtRenderer

=item *

Moose

=item *

Net::DNS

=item *

Number::Bytes::Human

=item *

Perl::Critic

=item *

Pod::Perldoc

=item *

Pod::POM::Web

=item *

Role::Tiny

=item *

Rose::DB

=item *

Rose::DB::Object

=item *

Scalar::Does

=item *

Sereal::Decoder

=item *

Sereal::Encoder

=item *

Shell::Config::Generate

=item *

Shell::Guess

=item *

String::Template

=item *

Template

=item *

Template::Tiny

=item *

Test::Differences

=item *

Test::Dir

=item *

Test::EOL

=item *

Test::File

=item *

Test::Fixme

=item *

Test::Memory::Cycle

=item *

Test::NoTabs

=item *

Test::Pod

=item *

Test::Pod::Coverage

=item *

Test::Pod::Spelling::CommonMistakes

=item *

Test::Spelling

=item *

Test::Strict

=item *

TinyMake

=item *

Try::Tiny

=item *

URI

=item *

URI::Encode

=item *

Validate::Tiny

=item *

WebService::TwitterBootstrap::Download::Custom

=item *

XML::Rabbit

=item *

XML::Simple

=item *

XML::Writer

=item *

YAML

=item *

YAML::XS

=back

=head1 AUTHOR

Graham Ollis <plicease@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2012 by Graham Ollis.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

