=head1 NAME

Task::BeLike::Plicease - Modules Plicease Uses.

=head1 VERSION

version 0.1

=head1 SYNOPSIS

 cpan Task::BeLike::Plicease

=head1 DESCRIPTION

Modules that I like to have installed when I am doing my Perl thing.

=head1 AUTHOR

Graham Ollis <plicease@wdlabs.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2012 by Graham Ollis.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

