#!/usr/bin/env perl

use strict;
use warnings;
use v5.10;
use File::Spec;
use Config::INI::Reader;

open my $fh, '<', File::Spec->catfile( qw( lib Task BeLike Plicease.pm ));
my @lines = <$fh>;
chomp @lines;
close $fh;

my $config = Config::INI::Reader->read_file('dist.ini');
my @modules = sort{ lc $a cmp lc $b } keys %{ $config->{Prereqs} };

open $fh, '>', File::Spec->catfile( qw( lib Task BeLike Plicease.pm ));

while(defined $lines[0])
{
  $_ = shift @lines;
  say $fh $_;
  last if /^=over 4\s*$/
}

while(defined $lines[0])
{
  $_ = shift @lines;
  last if /^=back\s*$/;
}

foreach my $module (@modules)
{
  say $fh "";
  say $fh "=item *";
  say $fh "";
  say $fh "$module";
}

say $fh "";
say $fh "=back";

while(defined $lines[0])
{
  $_ = shift @lines;
  say $fh $_;
}

close $fh;

# TODO write out a test that does a require_ok on each module
# making sure not to require_ok for the modules where the 
# platform doesn't include it.

exit 0;
