#!/usr/bin/env perl

use strict;
use warnings;
use autodie qw( :system );
use v5.10;

my $tgz = shift;
my @cmd = ('scp', $tgz, 'ollisg@matrix.wdlabs.com:/home/ollisg/web/sites/dist');
say "% @cmd";

eval { system @cmd };
if(my $error = $@)
{
  say "ERROR! $error";
}
